"""OpenAI-backed generation service for cloze variant endpoints."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re
from typing import Any

from openai import APIConnectionError, APIStatusError, APITimeoutError, OpenAI
from pydantic import BaseModel

from app.core.config import Settings
from app.core.errors import ApiError
from app.services.utils import TokenUsage, _extract_usage, _load_system_prompt


PROMPT_VERSION = "varc_v1"
SYSTEM_PROMPT_FILE = Path(__file__).resolve().parents[1] / "prompts" / f"{PROMPT_VERSION}_system_prompt.txt"
_CLOZE_MARKER_RE = re.compile(r"\{\{c(?P<index>\d+)::(?P<answer>.*?)(?:::(?P<hint>.*?))?\}\}")


@dataclass(frozen=True)
class ClozeVariantConstraints:
    """Behavior flags for cloze variant generation constraints."""

    no_trick_questions: bool
    keep_length_similar: bool


@dataclass(frozen=True)
class ClozeVariantGenerationInput:
    """Input payload consumed by the OpenAI cloze variant service."""

    cloze_text: str
    number_variations: int
    language: str
    style: str
    difficulty: str
    constraints: ClozeVariantConstraints


@dataclass(frozen=True)
class ClozeVariantItem:
    """A single generated cloze variant item for API response payloads."""

    cloze_text: str
    type: str = "cloze"


@dataclass(frozen=True)
class ClozeVariantResult:
    """Structured output consumed by the static API endpoint."""

    items: list[ClozeVariantItem]
    model: str
    usage: TokenUsage
    prompt_version: str = PROMPT_VERSION


class _StructuredVariantItem(BaseModel):
    """Structured output schema for a single cloze variant generated by OpenAI."""

    cloze_text: str


class _StructuredVariantOutput(BaseModel):
    """Structured output schema used by OpenAI responses.parse."""

    items: list[_StructuredVariantItem]


def generate_cloze_variants(payload: ClozeVariantGenerationInput, settings: Settings) -> ClozeVariantResult:
    """Generate cloze variants via OpenAI Responses API and normalize the output."""
    api_key = settings.openai_api_key.strip()
    if not api_key:
        raise ApiError(
            status_code=503,
            code="AI_PROVIDER_NOT_CONFIGURED",
            message="OpenAI API key is not configured",
        )

    required_targets = _extract_required_cloze_targets(payload.cloze_text)
    request_body = _build_openai_request(payload)
    response_json = _call_openai_responses_parse(request_body, settings, api_key)
    raw_items = _extract_items_from_response(response_json)
    normalized_cloze_texts = _normalize_cloze_variants(raw_items, payload, required_targets)

    items = [ClozeVariantItem(cloze_text=value) for value in normalized_cloze_texts]
    usage = _extract_usage(response_json)
    model = str(response_json.get("model") or settings.openai_model)
    return ClozeVariantResult(items=items, model=model, usage=usage)


def _build_openai_request(payload: ClozeVariantGenerationInput) -> dict[str, Any]:
    """Build a structured output request for cloze variant generation."""
    constraints: list[str] = []
    if payload.constraints.no_trick_questions:
        constraints.append("Do not create trick questions")
    if payload.constraints.keep_length_similar:
        constraints.append("Keep each variant roughly similar in length to the source")

    constraints_text = "; ".join(constraints) if constraints else "No extra constraints"
    system_prompt = _load_system_prompt(
        SYSTEM_PROMPT_FILE,
        load_error_message="Failed to load cloze variant system prompt",
        empty_error_message="Cloze variant system prompt file is empty",
    )

    prompt_lines = [
        f"Original cloze text: {payload.cloze_text}",
        f"Style: {payload.style}",
        f"Difficulty: {payload.difficulty}",
        f"Count: {payload.number_variations}",
        f"Constraints: {constraints_text}",
        "Generate unique cloze variants.",
    ]
    if payload.language.strip() != "auto":
        prompt_lines.insert(1, f"Target language: {payload.language}")
    user_prompt = "\n".join(prompt_lines)

    return {
        "input": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        "text_format": _StructuredVariantOutput,
    }


def _call_openai_responses_parse(body: dict[str, Any], settings: Settings, api_key: str) -> dict[str, Any]:
    """Call OpenAI Responses parse API and return normalized structured data."""
    client = OpenAI(
        api_key=api_key,
        base_url=settings.openai_base_url.rstrip("/"),
        timeout=settings.openai_timeout_seconds,
    )

    try:
        response = client.responses.parse(
            model=settings.openai_model,
            input=body["input"],
            text_format=body["text_format"],
        )
    except APITimeoutError as exc:
        raise ApiError(
            status_code=502,
            code="UPSTREAM_AI_ERROR",
            message="OpenAI request timed out",
            details={"error_type": exc.__class__.__name__},
        ) from exc
    except APIConnectionError as exc:
        raise ApiError(
            status_code=502,
            code="UPSTREAM_AI_ERROR",
            message="Failed to contact OpenAI",
            details={"error_type": exc.__class__.__name__},
        ) from exc
    except APIStatusError as exc:
        raise ApiError(
            status_code=502,
            code="UPSTREAM_AI_ERROR",
            message="OpenAI returned an error response",
            details={"upstream_status_code": exc.status_code},
        ) from exc

    parsed_output = response.output_parsed
    if parsed_output is None:
        raise ApiError(
            status_code=502,
            code="UPSTREAM_AI_ERROR",
            message="OpenAI response did not match structured output schema",
        )
    if not isinstance(parsed_output, _StructuredVariantOutput):
        raise ApiError(
            status_code=502,
            code="UPSTREAM_AI_ERROR",
            message="OpenAI structured output type mismatch",
        )

    usage = response.usage
    usage_payload = {
        "input_tokens": int(getattr(usage, "input_tokens", 0) or 0),
        "output_tokens": int(getattr(usage, "output_tokens", 0) or 0),
    }
    return {
        "items": [{"cloze_text": item.cloze_text} for item in parsed_output.items],
        "usage": usage_payload,
        "model": getattr(response, "model", settings.openai_model),
    }


def _extract_items_from_response(response_json: dict[str, Any]) -> list[str]:
    """Extract a list of cloze-text strings from normalized structured output."""
    items = response_json.get("items") if isinstance(response_json, dict) else None
    if not isinstance(items, list) or not items:
        raise ApiError(
            status_code=502,
            code="UPSTREAM_AI_ERROR",
            message="OpenAI response missing structured items",
        )

    cloze_texts: list[str] = []
    for raw_item in items:
        if not isinstance(raw_item, dict):
            continue
        raw_text = raw_item.get("cloze_text")
        if not isinstance(raw_text, str):
            continue
        normalized = raw_text.strip()
        if normalized:
            cloze_texts.append(normalized)

    if not cloze_texts:
        raise ApiError(
            status_code=502,
            code="UPSTREAM_AI_ERROR",
            message="OpenAI response contained no valid cloze text items",
        )
    return cloze_texts


def _extract_cloze_targets(cloze_text: str) -> list[tuple[str, str]]:
    """Extract normalized `(index, answer)` tuples for all cloze markers in order."""
    return [
        (match.group("index"), " ".join(match.group("answer").split()))
        for match in _CLOZE_MARKER_RE.finditer(cloze_text)
    ]


def _extract_required_cloze_targets(cloze_text: str) -> list[tuple[str, str]]:
    """Extract cloze targets and ensure the source text contains at least one marker."""
    targets = _extract_cloze_targets(cloze_text)
    if not targets:
        raise ApiError(
            status_code=400,
            code="INVALID_REQUEST",
            message="cloze_text must contain at least one cloze marker like {{c1::term}}",
        )
    return targets


def _normalize_cloze_variants(
    raw_items: list[str],
    payload: ClozeVariantGenerationInput,
    required_targets: list[tuple[str, str]],
) -> list[str]:
    """Deduplicate variants, enforce cloze-target preservation, and fill deterministic fallbacks."""
    deduped: list[str] = []
    seen: set[str] = set()

    for cloze_text in raw_items:
        if _extract_cloze_targets(cloze_text) != required_targets:
            continue
        fingerprint = cloze_text.casefold()
        if fingerprint in seen:
            continue
        seen.add(fingerprint)
        deduped.append(cloze_text)
        if len(deduped) == payload.number_variations:
            return deduped

    if len(deduped) < payload.number_variations:
        fillers = _build_fallback_cloze_variants(payload, count=payload.number_variations - len(deduped))
        for filler in fillers:
            fingerprint = filler.casefold()
            if fingerprint in seen:
                continue
            seen.add(fingerprint)
            deduped.append(filler)
            if len(deduped) == payload.number_variations:
                break

    while len(deduped) < payload.number_variations:
        idx = len(deduped) + 1
        deduped.append(f"Variant {idx}: {payload.cloze_text.strip()}")
    return deduped[: payload.number_variations]


def _build_fallback_cloze_variants(payload: ClozeVariantGenerationInput, count: int) -> list[str]:
    """Create deterministic safe fallbacks that preserve cloze markers verbatim."""
    source = payload.cloze_text.strip()
    templates = [
        f"Exam-style variant: {source}",
        f"{source} ({payload.difficulty} difficulty)",
        f"{source} [style:{payload.style}]",
        f"{source} [language:{payload.language}]",
        f"Concept check: {source}",
    ]
    return [templates[index % len(templates)] for index in range(count)]
