"""OpenAI-backed generation service for question variant endpoints."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from openai import APIConnectionError, APIStatusError, APITimeoutError, OpenAI
from pydantic import BaseModel

from app.core.config import Settings
from app.core.errors import ApiError
from app.services.utils import TokenUsage, _extract_usage, _load_system_prompt


PROMPT_VERSION = "varq_v4"
SYSTEM_PROMPT_FILE = Path(__file__).resolve().parents[1] / "prompts" / f"{PROMPT_VERSION}_system_prompt.txt"


@dataclass(frozen=True)
class QuestionVariantConstraints:
    """Behavior flags for variant generation constraints."""

    no_trick_questions: bool
    keep_length_similar: bool


@dataclass(frozen=True)
class QuestionVariantGenerationInput:
    """Input payload consumed by the OpenAI question variant service."""

    question: str
    answer: str
    number_variations: int
    language: str
    style: str
    difficulty: str
    constraints: QuestionVariantConstraints


@dataclass(frozen=True)
class QuestionVariantItem:
    """A single generated variant item for API response payloads."""

    question: str
    type: str = "open"


@dataclass(frozen=True)
class QuestionVariantResult:
    """Structured output consumed by the static API endpoint."""

    items: list[QuestionVariantItem]
    model: str
    usage: TokenUsage
    prompt_version: str = PROMPT_VERSION


# Schema for structered outputs
class _StructuredVariantItem(BaseModel):
    """Structured output schema for a single variant generated by OpenAI."""

    question: str


class _StructuredVariantOutput(BaseModel):
    """Structured output schema used by OpenAI responses.parse."""

    items: list[_StructuredVariantItem]


def generate_question_variants(payload: QuestionVariantGenerationInput, settings: Settings) -> QuestionVariantResult:
    """Generate question variants via OpenAI Responses API and normalize the output."""
    api_key = settings.openai_api_key.strip()
    if not api_key:
        raise ApiError(
            status_code=503,
            code="AI_PROVIDER_NOT_CONFIGURED",
            message="OpenAI API key is not configured",
        )

    request_body = _build_openai_request(payload)
    response_json = _call_openai_responses_parse(request_body, settings, api_key)

    raw_items = _extract_items_from_response(response_json)
    normalized_questions = _normalize_variant_questions(raw_items, payload)

    items = [QuestionVariantItem(question=question) for question in normalized_questions]
    usage = _extract_usage(response_json)
    model = str(response_json.get("model") or settings.openai_model)
    return QuestionVariantResult(items=items, model=model, usage=usage)


def _build_openai_request(payload: QuestionVariantGenerationInput) -> dict[str, Any]:
    """Build a structured output request for question variant generation."""
    constraints: list[str] = []
    if payload.constraints.no_trick_questions:
        constraints.append("Do not create trick questions")
    if payload.constraints.keep_length_similar:
        constraints.append("Keep each variant roughly similar in length to the source question")

    constraints_text = "; ".join(constraints) if constraints else "No extra constraints"
    system_prompt = _load_system_prompt(
        SYSTEM_PROMPT_FILE,
        load_error_message="Failed to load question variant system prompt",
        empty_error_message="Question variant system prompt file is empty",
    )
    user_prompt = (
        f"Original question: {payload.question}\n"
        f"Reference answer: {payload.answer}\n"
        f"Target language: {payload.language}\n" if payload.language.strip() != "auto" else ""  # avoid mentioning language if auto-detection is requested
        f"Style: {payload.style}\n"
        f"Difficulty: {payload.difficulty}\n"
        f"Count: {payload.number_variations}\n"
        f"Constraints: {constraints_text}\n"
        "Generate unique variants."
    )

    return {
        "input": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        "text_format": _StructuredVariantOutput,
    }


def _call_openai_responses_parse(body: dict[str, Any], settings: Settings, api_key: str) -> dict[str, Any]:
    """Call OpenAI Responses parse API and return normalized structured data."""
    client = OpenAI(
        api_key=api_key,
        base_url=settings.openai_base_url.rstrip("/"),
        timeout=settings.openai_timeout_seconds,
    )

    try:
        response = client.responses.parse(
            model=settings.openai_model,
            input=body["input"],
            text_format=body["text_format"],
        )

    # handle exceptions from the OpenAI client and convert to API errors with appropriate status codes.
    except APITimeoutError as exc:
        raise ApiError(
            status_code=502,
            code="UPSTREAM_AI_ERROR",
            message="OpenAI request timed out",
            details={"error_type": exc.__class__.__name__},
        ) from exc
    except APIConnectionError as exc:
        raise ApiError(
            status_code=502,
            code="UPSTREAM_AI_ERROR",
            message="Failed to contact OpenAI",
            details={"error_type": exc.__class__.__name__},
        ) from exc
    except APIStatusError as exc:
        raise ApiError(
            status_code=502,
            code="UPSTREAM_AI_ERROR",
            message="OpenAI returned an error response",
            details={"upstream_status_code": exc.status_code},
        ) from exc

    parsed_output = response.output_parsed
    if parsed_output is None:
        raise ApiError(
            status_code=502,
            code="UPSTREAM_AI_ERROR",
            message="OpenAI response did not match structured output schema",
        )

    if not isinstance(parsed_output, _StructuredVariantOutput):
        raise ApiError(
            status_code=502,
            code="UPSTREAM_AI_ERROR",
            message="OpenAI structured output type mismatch",
        )

    usage = response.usage
    usage_payload = {
        "input_tokens": int(getattr(usage, "input_tokens", 0) or 0),
        "output_tokens": int(getattr(usage, "output_tokens", 0) or 0),
    }

    return {
        "items": [{"question": item.question} for item in parsed_output.items],
        "usage": usage_payload,
        "model": getattr(response, "model", settings.openai_model),
    }


def _extract_items_from_response(response_json: dict[str, Any]) -> list[str]:
    """Extract a list of question strings from normalized structured output."""
    items = response_json.get("items") if isinstance(response_json, dict) else None
    if not isinstance(items, list) or not items:
        raise ApiError(
            status_code=502,
            code="UPSTREAM_AI_ERROR",
            message="OpenAI response missing structured items",
        )

    questions: list[str] = []
    for raw_item in items:
        if not isinstance(raw_item, dict):
            continue

        raw_question = raw_item.get("question")
        if not isinstance(raw_question, str):
            continue

        normalized = raw_question.strip()
        if normalized:
            questions.append(normalized)

    if not questions:
        raise ApiError(
            status_code=502,
            code="UPSTREAM_AI_ERROR",
            message="OpenAI response contained no valid questions",
        )

    return questions


def _normalize_variant_questions(raw_items: list[str], payload: QuestionVariantGenerationInput) -> list[str]:
    """Deduplicate variants and enforce exact output count with deterministic fillers."""
    deduped: list[str] = []
    seen: set[str] = set()

    # First pass to identify deduplicate while preserving order
    for question in raw_items:
        fingerprint = question.casefold()
        if fingerprint in seen:
            continue
        seen.add(fingerprint)
        deduped.append(question)

        # enough unique variants, return early without needing fillers
        if len(deduped) == payload.number_variations:
            return deduped

    # Fewer unique variants than requested, add deterministic fallback variants to fill the gap.
    if len(deduped) < payload.number_variations:
        fillers = _build_fallback_questions(payload, count=payload.number_variations - len(deduped))
        for filler in fillers:
            fingerprint = filler.casefold()
            if fingerprint in seen:
                continue
            seen.add(fingerprint)
            deduped.append(filler)
            if len(deduped) == payload.number_variations:
                break

    while len(deduped) < payload.number_variations:
        idx = len(deduped) + 1
        deduped.append(f"{payload.question.strip()} (Variant {idx})")

    return deduped[: payload.number_variations]


def _build_fallback_questions(payload: QuestionVariantGenerationInput, count: int) -> list[str]:
    """Create deterministic safe rewrites if provider output is undersized."""
    base = payload.question.strip().rstrip("?.!")
    templates = [
        f"In {payload.style} style, explain: {base}?",
        f"{base} Please answer at a {payload.difficulty} difficulty level.",
        f"Using {payload.language}, restate and answer: {base}?",
        f"What is the best concise response to: {base}?",
        f"Provide a clear explanation for: {base}?",
    ]

    return [templates[index % len(templates)] for index in range(count)]
